import Head from "next/head";
import React from "react";

const index = () => {
  return (
    <>
      <Head>
        <title>App: Section 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <h2 className="text-3xl mb-2">Section 2</h2>
        <>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
          <p>Section 2</p>
        </>
      </>
    </>
  );
};

export default index;
